version: "3"

services:
  chirpstack-network-server:
    image: chirpstack/chirpstack-network-server:3
    volumes:
      - ./configuration/chirpstack-network-server:/etc/chirpstack-network-server
    dns:
      8.8.8.8
  chirpstack-application-server:
    image: chirpstack/chirpstack-application-server:3
    ports:
      - 8080:8080
    volumes:
      - ./configuration/chirpstack-application-server:/etc/chirpstack-application-server
    dns:
      8.8.8.8
  chirpstack-gateway-bridge:
    image: chirpstack/chirpstack-gateway-bridge:3
    ports:
      - 1701:1700/udp
    volumes:
      - ./configuration/chirpstack-gateway-bridge:/etc/chirpstack-gateway-bridge
    dns:
      8.8.8.8
  chirpstack-geolocation-server:
    image: chirpstack/chirpstack-geolocation-server:3
    volumes:
      - ./configuration/chirpstack-geolocation-server:/etc/chirpstack-geolocation-server
    dns:
      8.8.8.8
  postgresql:
    image: postgres:9.6-alpine
    environment:
      - POSTGRES_PASSWORD=root
    volumes:
      - ./configuration/postgresql/initdb:/docker-entrypoint-initdb.d
      - postgresqldata:/var/lib/postgresql/data
    dns:
      8.8.8.8
  redis:
    image: redis:5-alpine
    volumes:
      - redisdata:/data
    dns:
      8.8.8.8
  mosquitto:
    image: eclipse-mosquitto
    ports:
      - 1883:1883
    dns:
      8.8.8.8
  influxdb:
    image: influxdb
    ports:
      - 8086:8086
    dns:
      8.8.8.8
  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    dns:
      8.8.8.8
volumes:
  postgresqldata:
  redisdata:
